-- create database MyDatabase
--CREATE DATABASE SUrPic_DB

USE SUrPic;

CREATE TABLE ACCOUNT (
    USERNAME VARCHAR(50) PRIMARY KEY,
    HASH_PASSWORD VARCHAR(50)
);

CREATE TABLE PICTURE(
	ID INT IDENTITY(0,1) PRIMARY KEY,
	NAME VARCHAR(256),
	OWNER VARCHAR(50),
	PATH VARCHAR(500),
	TAGS VARCHAR(8000)
);

CREATE TABLE FOLLOW(
	FOLLOWER VARCHAR(50),
	BE_FOLLOW VARCHAR(50),
	PRIMARY KEY (FOLLOWER,BE_FOLLOW)
);

CREATE TABLE SAVE_PIC(
	SAVER VARCHAR(50),
	BE_SAVE INT,
	PRIMARY KEY (SAVER,BE_SAVE)
);

ALTER TABLE PICTURE
ADD FOREIGN KEY (OWNER) REFERENCES ACCOUNT(USERNAME);

ALTER TABLE FOLLOW
ADD FOREIGN KEY (FOLLOWER) REFERENCES ACCOUNT(USERNAME);
ALTER TABLE FOLLOW
ADD FOREIGN KEY (BE_FOLLOW) REFERENCES ACCOUNT(USERNAME);

ALTER TABLE SAVE_PIC
ADD FOREIGN KEY (SAVER) REFERENCES ACCOUNT(USERNAME);
ALTER TABLE SAVE_PIC
ADD FOREIGN KEY (BE_SAVE) REFERENCES PICTURE(ID);








